name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  dp-standards-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: |
          *.md
